#ifndef CODES_H_INCLUDED
#define CODES_H_INCLUDED

#define EXIT_ERROR_NOERROR 0
#define EXIT_ERROR_NOARGS 1
#define EXIT_ERROR_FILEIO 2
#define EXIT_ERROR_IMAGED 3
#define EXIT_ERROR_CL_COMPILE 4
#define EXIT_ERROR_CL_INIT 5


#endif // CODES_H_INCLUDED
