#ifndef SETTINGS_INCLUDED
#define SETTINGS_INCLUDED

#define NO_TEST_CV
#define NO_TEST_COMMANDS
#define NO_TEST_COLOR
//#define NO_DEBUG_PRINT

#define COLOR_SEPERATOR :

#endif // SETTINGS_INCLUDED
